services:
  - docker
os:
  - linux
dist: trusty
cache:
  yarn: true
  directories:
    - node_modules
  # use container-based build env for faster boot
sudo: true
addons:
  chrome: stable
language: node_js

node_js:
  - "10"

before_install: yarn global add greenkeeper-lockfile
install:
  - git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG
  - git checkout -qf $TRAVIS_COMMIT
  - case $TRAVIS_BRANCH in greenkeeper*) yarn install;; *) esac;

before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

script:
  - yarn install
  - yarn run build
